version: '3.8'

services:
  ## Recommended to run `npm run dev` instead
  # app:
  #   build:
  #     context: .
  #   ports:
  #     - '5000:5000'
  #   environment:
  #     - DB_HOST=db
  #     - DB_NAME=${DB_NAME}
  #     - DB_USER=${DB_USER}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #     - JWT_SECRET=${JWT_SECRET}
  #     - POSTGRES_URL=${POSTGRES_URL}
  #   depends_on:
  #     - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  postgres_data:
