name: Build and deploy Node.js app to Azure Web App - task-manager-dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        working-directory: ./api
        run: npm install

      - name: Build the application
        working-directory: ./api
        run: npm run build

      - name: Zip artifact for deployment
        run: |
          cd ./api/dist
          zip -r ../../release.zip . -x '*.git*' -x 'node_modules/*' -x 'tests/*'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_807524D08CB44372AE167473E5E86F1F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F7E6D73DC04C4EEDBC7037675553F1E1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7C6211D0159D4B7F825DEB0A43255A6A }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'task-manager-dev'
          slot-name: 'Production'
          package: .
          